#!/usr/bin/env python3
"""
Minimal server to verify password and save allowed WAN IPs.

Place this file in the same directory as:
- passwords.json   (generated by your generator)
- password.html
- s1rfxuj9yk.html

Run: python3 server.py
"""

import os
import json
import base64
import hashlib
from flask import Flask, request, session, jsonify, abort

APP_DIR = os.path.dirname(os.path.abspath(__file__))
PASSWORDS_FILE = os.path.join(APP_DIR, "passwords.json")
ALLOWED_FILE = os.path.join(APP_DIR, "allowed_ips.json")
SESSION_KEY_FILE = os.path.join(APP_DIR, "session.key")

# Serve static files from the same directory so password.html and the protected page
# are available at http://<host>:8000/password.html and /s1rfxuj9yk.html
app = Flask(__name__, static_folder=".", static_url_path="")

# Session key: create or reuse a file so sessions persist across restarts
if os.path.exists(SESSION_KEY_FILE):
    with open(SESSION_KEY_FILE, "rb") as f:
        app.secret_key = f.read()
else:
    key = os.urandom(32)
    with open(SESSION_KEY_FILE, "wb") as f:
        f.write(key)
    os.chmod(SESSION_KEY_FILE, 0o600)
    app.secret_key = key

# Cookie settings for testing; set SESSION_COOKIE_SECURE=True in production with HTTPS
app.config.update(SESSION_COOKIE_HTTPONLY=True, SESSION_COOKIE_SECURE=False, SESSION_COOKIE_SAMESITE="Lax")


def load_password_cfg():
    with open(PASSWORDS_FILE, "r") as f:
        return json.load(f)


def verify_password(password: str, cfg: dict) -> bool:
    """PBKDF2-SHA256 derive and compare to stored base64 hash."""
    salt = base64.b64decode(cfg["salt"])
    iterations = int(cfg["iterations"])
    dk = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, iterations, dklen=32)
    return base64.b64encode(dk).decode("utf-8") == cfg["hash"]


def load_allowed_ips():
    if not os.path.exists(ALLOWED_FILE):
        return []
    with open(ALLOWED_FILE, "r") as f:
        try:
            return json.load(f)
        except Exception:
            return []


def save_allowed_ips(ips):
    with open(ALLOWED_FILE, "w") as f:
        json.dump(ips, f)
    os.chmod(ALLOWED_FILE, 0o600)


@app.route("/login", methods=["POST"])
def login():
    """
    Expects JSON body: { "password": "...", "remember": true|false }
    On success:
      - sets a session flag
      - if remember true, appends request.remote_addr to allowed_ips.json (if not present)
    """
    data = request.get_json(silent=True) or {}
    password = data.get("password", "")
    remember = bool(data.get("remember", False))

    try:
        cfg = load_password_cfg()
    except FileNotFoundError:
        abort(500, "passwords.json missing on server")

    if not verify_password(password, cfg):
        return jsonify({"ok": False, "error": "invalid"}), 401

    session.clear()
    session["authed"] = True

    if remember:
        ip = request.remote_addr
        ips = load_allowed_ips()
        if ip not in ips:
            ips.append(ip)
            save_allowed_ips(ips)

    return jsonify({"ok": True})


@app.route("/check_access", methods=["GET"])
def check_access():
    """
    Returns JSON { ok: true } if:
      - session is authenticated OR
      - request.remote_addr is present in allowed_ips.json
    Otherwise returns 401 with { ok: false }.
    """
    if session.get("authed"):
        return jsonify({"ok": True, "by": "session"})

    ip = request.remote_addr
    ips = load_allowed_ips()
    if ip in ips:
        return jsonify({"ok": True, "by": "ip"})

    return jsonify({"ok": False}), 401


@app.route("/logout", methods=["POST"])
def logout():
    session.clear()
    return jsonify({"ok": True})


if __name__ == "__main__":
    # For local testing use port 8000. Use a reverse proxy and HTTPS in production.
    app.run(host="0.0.0.0", port=8000)
